import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { cn } from '@/utils/style';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          'isolate grid place-items-center bg-white text-content ',
          inter.className
        )}
      >
        <div className="h-screen min-h-screen w-screen">
          <div className="flex flex-1 flex-col">
            <div className="mx-40 flex flex-1 flex-col">
              <Header />
              <main className="flex flex-1 flex-col">{children}</main>
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
